##server配置##
server:
  port: 8888
  servlet:
    session:
      timeout: 3600s
    context-path: /halcyon


spring:
  profiles:
    active: dev
  activiti:
    async-executor-activate: true
    mail-server-use-ssl: true
    #自动更新数据库
    database-schema-update: false
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: false
    #restApiEnabled: false
    jpa-enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/halcyon?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: marshal1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HalcyonHikariCP

  #redis
  redis:
    host: localhost
    port: 6379
    password:
    database: 10
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 100ms

  jms:
    pub-sub-domain: true

  #  activemq:
  #    broker-url: tcp://132.232.243.120:61616
  #    in-memory: false
  #    close-timeout: 15s


  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    favicon:
      enabled: true

  data:
    solr:
      host: http://localhost:8080/solr/halcyon-core
      repositories:
        enabled: true
      default-field: hal_keywords

  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html


  ################################
  #####  Spring QUARTZ  ##########
  ################################
  quartz:
    #随项目启动而启动开关
    auto-startup: false
    #调度器名称-对象名
    scheduler-name: quartzScheduler
    #存储方式
    job-store-type: jdbc
    #额外属性
    properties:
      org:
        quartz:
          scheduler:
            #调度器类型
            instanceName: DefaultQuartzScheduler
            #每个集群节点要有独立的instanceId
            instanceId: AUTO
          #线程池
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 20
            threadPriority: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #为false则jobData类型只能为String
            useProperties: false
            #集群
            isClustered: true
            clusterCheckinInterval: 15000
            maxMisfiresToHandleAtATime: 1
            misfireThreshold: 12000
            tablePrefix: QRTZ_
          #插件配置
          plugin:
            #调度器监听器
            runningListener:
              class: com.marshal.halcyon.quartz.plugin.RunningListenerPlugin
              LogRunningInfo: true
  ################################
  #####  Spring QUARTZ  ##########
  ################################



  ################################
  #####  Spring Mail    ##########
  ################################
  # 邮件发送
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 453607106@qq.com
    #授权码/密码
    password:
    port: 25
    protocol: smtp
  ################################
  #####  Spring Mail    ##########
  ################################



# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#  configuration:
#    jdbc-type-for-null: null

# 通用 mapper插件配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: mysql

# pagehelper插件配置（分页）
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 时间类型格式化，时区为 +8区


##########################################
############  Custom Prop    #############
############  @自定义属性     #############
##########################################
security:
  login-url: /login
  logout-url: /logout
  login-page: /login.html
  default-target-url: /index.html
  authentication-failure-url: /login.html
  static-resources: /static/**,/login/**,/css/**,/js/**,/diagram-viewer/**,/editor-app/**,/images/**,/plugins/**
  #数组写法[a,b,c]
##########################################
############  Custom Prop    #############
##########################################
